a = input("Digite algo: ")

print('O tipo primitivo desse valor é: ', type(a))
print('Só tem espaços? ', a.isspace())
print('É númerico?', a.isnumeric())
print('È alfabético?', a.isalpha())
print('É alfabético e númerico?', a.isalnum())
print('Está em maiúsculo?', a.isupper())
print('Está em minúsculo?', a.islower())
print('Está capitalizada?', a.istitle())